language: python
python:
  - "2.7"
before_install:
  - "pip install codecov"
install:
  - "pip install -r requirements.txt"
script: nosetests --with-coverage casino/ matchmaker/
after_success:
  - "codecov"
